name: DBT CI/CD

on:
 push:
  branches:
     - dev
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake
      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          demo_snowflake_dbt:
            outputs:
              dev:
                account: $SNOWFLAKE_ACCOUNT
                private_key: $SNOWFLAKE_PRIVATE_KEY
                role: $SNOWFLAKE_ROLE
                threads: 4
                type: snowflake
                user: $SNOWFLAKE_USER
                warehouse: $SNOWFLAKE_WAREHOUSE
            target: dev
          " > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: github
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      - name: DBT debug
        run: dbt debug

      - name: DBT deps
        run: dbt deps

      # - name: DBT test
      #   run: dbt test

  dbt_cd:
    runs-on: ubuntu-latest
    needs: dbt_ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install DBT and Snowflake adapter
        run: |
          pip install dbt-core dbt-snowflake
      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          demo_snowflake_dbt:
            outputs:
              dev:
                account: $SNOWFLAKE_ACCOUNT
                private_key: $SNOWFLAKE_PRIVATE_KEY
                role: $SNOWFLAKE_ROLE
                threads: 4
                type: snowflake
                user: $SNOWFLAKE_USER
                warehouse: $SNOWFLAKE_WAREHOUSE
            target: dev
          " > ~/.dbt/profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: github
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      - name: DBT deps
        run: dbt deps

      - name: DBT run
        run: dbt run